name: The GrowthMinded Blog
favicon: null
layout_spectrum: 0.19873410556465387
typography_spectrum: 0.22541275015100837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6d6d6'
    - '#2f2f2f'
    - '#f1f1f1'
    - '#3d5660'
    - '#7598a3'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.9509132963139564
purpose: []
