name: The GrowthMinded Blog
favicon: null
layout_spectrum: 0.19873410556465387
typography_spectrum: 0.22541275015100837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.06774534308351576
  lightness: 0.30179754039272666
  saturation: 0.262225063983351
  rhythmicContrast: 0.9509132963139564
purpose: []
